### ISSUE TITLE
Add identifier to manifest.json

### ISSUE THREAD

**Issue by mludowise** [philsinatra/Sketch-Color-Vars#1]
This plugin cannot automatically update in [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) because it is missing an identifier in the manifest.json file. See http://developer.sketchapp.com/introduction/plugin-bundles/ for more info.

**Comment by philsinatra** [comment]
I must have forgot to fill that in when I set the plugin up. Thanks for pointing that out. I've updated the _manifest.json_ file to include a unique identifier.
