### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [philsinatra/Sketch-Color-Vars#2]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by philsinatra** [comment]
I've updated the `manifest.json` and included the `appcast.xml` path. Any way to test the implementation ahead of time? I used Sketch daily; I'm weary of installing a beta version because it is a critical part of my workflow.

**Comment by bomberstudios** [comment]
I can test this for you, don't worry! 🙂

**Comment by bomberstudios** [comment]
You'll want to point you `appcast` entry to `https://raw.githubusercontent.com/philsinatra/Sketch-Color-Vars/master/appcast.xml`, so that Sketch downloads the raw XML, and to make sure it's always using the latest version.

Also, make sure the enclosure URL points to a plugin that contains an updated `manifest.json` (it currently downloads v1.1.1, which does not contain a reference to `appcast`).

Hope it helps!

**Comment by philsinatra** [comment]
Thanks for the details. I believe I have these fixes in place. Let me know if you're able to test again.

**Comment by bomberstudios** [comment]
Works like a charm, closing! 🎉
