### ISSUE TITLE
Plugin don't work for some users. 

### ISSUE THREAD

**Issue by mtgentry** [philsinatra/Sketch-Color-Vars#5]
Running OSX 10.13.5 and Sketch 45. When selecting all layers and then clicking the plugin, nothing happens. See here: https://www.dropbox.com/s/yo6k08avkyoxkx3/colors.mov?dl=0

**Comment by petrchutny** [comment]
Same, Sketch 51, OS X 10.13.1.

**Comment by philsinatra** [comment]
I'm able to replicate this issue, looking into it.

**Comment by philsinatra** [comment]
Fixed in version 1.3.2

**Comment by mtgentry** [comment]
thanks @philsinatra works great!
